### PR TITLE
Change "unknown" to "?" in the Ok? db jobs field

### PR DESCRIPTION
**Pull request by ammernico**
<details>

</details>

### CODE REVIEW

**Review by michaelweiser — COMMENTED** [review]
Well, if I had any stakes in the project I wouldn't accept a commit without any explanation what it's supposed to be doing. :) I think this review request was accidentally routed to me. @christophprokop?

**Comment by ammernico** [comment]
@michaelweiser, whoops sorry selected the wrong michael weis in the reviewer selection. Will add a example to the commit message. Thank you for the feedback

**Review by primeos-work — APPROVED** [review]
Thanks :) I agree with @michaelweiser that this PR/commit should provide an explanation/reasoning for this change (as any commit/PR should).

Looks like we've missed this in https://github.com/science-computing/butido/pull/107.

One of the most important aspects of a commit message is to explain why a change was made (s. https://cbea.ms/git-commit/#why-not-how or other sources).

In this case our motivations are that the table should fit the text width of the terminal (so that the text wrapping doesn't destroy the table) and constant size / fixed width columns are preferred (to avoid the first issue, for more consistent output, etc.).

We should also link to https://github.com/science-computing/butido/issues/49#issuecomment-1332199047 where we documented the desired changes (although that issue also lacks a proper explanation of the reasons behind it - the commit message could simply refer to that issue for the reasoning/motivation if it were documented there).

I would also likely leave the example out of the commit message as the table will look "horrible" if the terminal width is too small (plus we could avoid that the optional commit lint CI check fails). You can put it in the PR description though (below the cut point for bors so that it won't end up in a commit message anyway) - on GitHub it would be a nice bonus for quickly seeing the difference.

Anyway, this could be merged as is but it could also be a good chance to practice writing good commit messages ;)

**Comment by ammernico** [comment]
bors merge

**Pull request merged**
