### PR TITLE
Fix: Buffer stream with buffer size 100

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This patch fixes an issue when there are too many futures in the
iterator, resulting in resource exhaution in the docker interface, where
the copying process fails because there's just too much.

## Checklist

* [x] all commits are `--signoff` (Why? See CONTRIBUTING.md)
* [x] No `!fixup` commits in the PR
* [x] I ran `cargo check --all --tests`
* [x] I ran `cargo test`
* [x] I ran `cargo clippy`

### CODE REVIEW

**Comment by christophprokop** [comment]
Thanks for your help! :)

**Comment by matthiasbeyer** [comment]
CI failed, why were you able to merge?

**Comment by christophprokop** [comment]
i was curious and just tried it - should a merge be blocked if CI does not pass all tests?

**Comment by matthiasbeyer** [comment]
> should a merge be blocked if CI does not pass all tests?

Yes

**Pull request merged**
