### PR TITLE
Link validity check

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Requires #28 , will rebase after #28 is merged.

---

This is a new feature that checks all package source URLs whether they are still valid, using the `lychee` library. It does _not_ download the source, but simply does a connection-check (see https://github.com/lycheeverse/lychee/blob/master/README.md) and thus only finds broken links, not changed sources.

## Checklist

* [x] all commits are `--signoff` (Why? See CONTRIBUTING.md)
* [x] No `!fixup` commits in the PR
* [ ] I ran `cargo check --all --tests`
* [ ] I ran `cargo test`
* [ ] I ran `cargo clippy`

### CODE REVIEW

**Comment by christophprokop** [comment]
bors try

**Comment by matthiasbeyer** [comment]
I guess the cargo-deny issue should be fixed by some dependabot update once it lands, because the crate in question might be updated. We'll see...

**Comment by christophprokop** [comment]
bors try

**Comment by primeos-work** [comment]
This is currently blocked on https://github.com/lycheeverse/lychee/issues/594. The [lychee-lib](https://crates.io/crates/lychee-lib) crate (currently v0.10.3) still depends on [check-if-email-exists](https://crates.io/crates/check-if-email-exists/0.9.0) (v0.9.0) which is under the [AGPL-3.0](https://choosealicense.com/licenses/agpl-3.0) license (i.e., incompatible with our non-copyleft license).

The easiest solution is to wait for https://github.com/lycheeverse/lychee/issues/594 to be resolved. Alternatively, we could switch to another crate.

**Comment by christophprokop** [comment]
Blocked due to license issues. Also this issue is not that important. The best link checker is to just re-download all the sources (which takes about an hour atm).

**Pull request closed without merging**
