### PR TITLE
Bors

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This implements the [bors](https://bors.tech) merge bot for this repository.

<details>
What you need to do:

- Go to https://bors.tech and log into the dashboard with your github credentials
- Create a new repository in the "repositories" tab (this one of course)
- Go to the repository settings for this repository and
  - Enable branch protection for "master" (if not already done)
  - With "Require a pull request before merging"
  - With "Require status checks to pass before merging"
  - With "bors" as only required status check. This might not be possible to select yet. If it is not, come back to this PR and comment "bors ping". Bors should reply with "pong" and after that it should be possible to set bors as required status check. If not, come back to me.
  - "Require pull request reviews before merging" MUST be unmarked
  - Required for administrators as well

**Do not merge this PR with the merge button!**

After everything is set-up, you cannot use the "Merge" button anymore. What you do instead is: If you want to merge a PR, you comment with "bors merge".

See also: [bors documentation](https://bors.tech/documentation/) and [getting started page](https://bors.tech/documentation/getting-started/).

If any questions come up, ping me (either here or via some other mechanism).

</details>

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@christophprokop ping.

**Comment by matthiasbeyer** [comment]
@christophprokop ping

**Comment by christophprokop** [comment]
bors ping

**Comment by christophprokop** [comment]
bors try

**Comment by christophprokop** [comment]
bors try

**Comment by matthiasbeyer** [comment]
Just to showcase:

bors try

**Comment by christophprokop** [comment]
bors merge

**Comment by matthiasbeyer** [comment]
Another round...

**Comment by christophprokop** [comment]
bors merge

**Comment by matthiasbeyer** [comment]
I am not going to fix the clippy stuff today.

As soon as I have everything green locally, I'll push it and then you can `bors merge` it.

**Comment by matthiasbeyer** [comment]
Or even better: If you want, you can delegate the PR to me!

**Comment by christophprokop** [comment]
bors delegate=matthiasbeyer

**Comment by christophprokop** [comment]
bros

**Comment by matthiasbeyer** [comment]
So much for "not today"...

Lets see what CI tells us. But I believe that if everything is green, we can

bors merge

this...

**Comment by matthiasbeyer** [comment]
The lint error on [a54efe7](https://github.com/science-computing/butido/pull/32/commits/a54efe7d20ee02ebc49176fe09ef28c235b6fabe) was kinda expected, lets see whether it persists with rustc 1.64. Locally it does not for me, so I'm positive that this will go through.

**Comment by matthiasbeyer** [comment]
Here we go.

bors merge

**Pull request merged**
