### PR TITLE
Fix: Number of args for --env in "build" subcommand

### LINKED ISSUE #42: CLI broken
After merging #41 

```
$ butido build tree -I local:rh8-default -L 1.8.0
error: Invalid value 'false' for '--env': Error during validation: 'Incomplete' is not a key-value pair
```

_Originally posted by @christophprokop in https://github.com/science-computing/butido/issues/41#issuecomment-1310389847_

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Fixes: a53f3bfd0622f1ee955af053c52f1d1577695c90 ("Rewrite value fetching")

Extracted from #43 
Closes #42 

---

I guess this closes #42, but please test. As far as I can see this patch is still valid, but YMMV.

### CODE REVIEW

**Comment by christophprokop** [comment]
crash report attached:
[report-93029cc4-d426-455f-ae77-b004657a6bcb.txt](https://github.com/science-computing/butido/files/9984979/report-93029cc4-d426-455f-ae77-b004657a6bcb.txt)

**Comment by matthiasbeyer** [comment]
Was this crash report made with this patch applied or without?

**Comment by matthiasbeyer** [comment]
Can you re-try now? I am not sure whether this fixes the issue... but if it does, there's more work to do.

**Comment by christophprokop** [comment]
identical crash report

**Comment by christophprokop** [comment]
temporary solution via #78

**Pull request closed without merging**
