### PR TITLE
Update clap

### PR DESCRIPTION
**Pull request by matthiasbeyer**
This updates the `clap` dependency to clap 4.0.

This is a bit more involved, as clap changed quite a bit between major versions. Also, this introduces more typing to the CLI parsing, which should result in less validation/parsing code down the road, which is really nice.

There are some improvements I plan to make for the CLI parsing code that are not yet included here, but I guess as a first step this is more than enough. Feel free to review extensively. I think testing this would also be nice, especially since I cannot and as the parsing behaviour of clap might have changed in subtle ways that are not covered by any integration tests in this repository (would be really nice to have some...)

### CODE REVIEW

**Comment by christophprokop** [comment]
Great! I tested with a few submits and arguments and it works great!
Merge right now or test some more? ;)

**Comment by matthiasbeyer** [comment]
I'd say if your basic stuff works, go ahead and merge this!
If it turns out to have broken something we can always roll back :wink:

**Comment by christophprokop** [comment]
move fast and break things? ;)
bors merge

**Comment by matthiasbeyer** [comment]
> move fast and break things? ;)

As long as CI is green, nothing is broken, right? :wink: 
We can actually take this as a check, ... if something breaks, we clearly need more testing in this repository! For example, integration tests are dearly missing here as well.

**Comment by christophprokop** [comment]
yeah, true :)

**Comment by christophprokop** [comment]
Of course right after merging if got this:

$ butido build tree -I local:rh8-default -L 1.8.0
error: Invalid value 'false' for '--env': Error during validation: 'Incomplete' is not a key-value pair

**Pull request merged**
